ws_url: ws://livekit:7880
api_key: devkey
api_secret: super_secret_123_456_secure_string_12

http_relay_port: 9090
http_relay_host: 127.0.0.1
rtmp_base_url: rtmp://localhost:1935/x
# rtmp_base_url: rtmp://livekit-ingress:1935/x

redis:
  address: websockets-redis:6379
  password: '12345'

logging:
  level: info