export enum WsErrorCodes {
  UNAUTHORIZED = 'CHAT_UNAUTHORIZED',
  ROOM_NOT_FOUND = 'CHAT_ROOM_NOT_FOUND',
  USER_BANNED = 'CHAT_USER_BANNED',
  MESSAGE_TOO_LONG = 'CHAT_MESSAGE_TOO_LONG',
  RATE_LIMIT_EXCEEDED = 'CHAT_SPAM_PROTECTION',
  INTERNAL_ERROR = 'CHAT_INTERNAL_ERROR',
}
